name: COM_Zombies
main: com.theprogrammingturkey.comz.COMZombies
description: 'Call of Minecraft: Zombies'
version: ${file.jarVersion}
authors: [Turkey2349]
api-version: '1.15'
load: POSTWORLD
commands:
  zombies:
    description: Type /zombies help for more info!
    aliases: [z, zo, zom]
